<?php

namespace AppBundle\Repository;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends \Doctrine\ORM\EntityRepository
{
    public function moviesQuery()
    {
        $movies = $this->createQueryBuilder('movies')
            /*->select("movies.id, movies.titre, date(movies.dateSortie), movies.description")*/
            /*->select('movies.titre AS t, movies.description AS d')*/
            /*->select('movies.titre')
            ->where("year(movies.dateSortie) > 1980 ")
            ->andWhere('movies.titre LIKE :paramLike')
            ->setParameters([
                'paramLike' => '%les%'
            ])*/
            /*->select('movies.titre')
            ->join('movies.realisateurs', 'directors')
            ->where('directors.prenom LIKE :paramPrenom')
            ->andWhere('directors.nom LIKE :paramNom')
            ->setParameters([
                'paramPrenom' => 'Akira',
                'paramNom' => 'Kurosawa'
            ])*/
            /* ->select(" genres.nom, GROUP_CONCAT (movies.titre SEPARATOR ' / ') AS titres")
            ->join('movies.realisateurs', 'directors')
            ->join('movies.genres', 'genres')
            ->where('directors.prenom LIKE :paramPrenom')
            ->andWhere('directors.nom LIKE :paramNom')
            ->setParameters([
               'paramPrenom' => 'Sergio',
               'paramNom' => 'Leone'
            ]) */
            /*->select('actors.nom')
            ->join('movies.acteurs', 'actors')
            ->join('movies.realisateurs', 'directors')
            ->join('actors.pays', 'countries')
            ->where('countries.nom  = :paramCountries')
            ->andWhere('directors.nom = :paramNom')
            ->andWhere('directors.prenom = :paramPrenom')
            ->setParameters([
                'paramPrenom' => 'Steven',
                'paramNom' => 'Spielberg',
                'paramCountries' => 'France'
            ])*/
            /*->select('movies.titre, date(movies.dateSortie), directors.nom')
            ->join('movies.realisateurs', 'directors')
            ->where('year(movies.dateSortie) >= 1990')
            ->andWhere('year(movies.dateSortie) < 2000')*/

            /*->select('actors.nom')
            ->join('movies.acteurs', 'actors')
            //->addOrderBy('actors.nom') ou ->->addOrderBy('actors.nom', 'ASC')
            ->addOrderBy('actors.nom', 'DESC')
            */
           /* ->select('directors.nom, COUNT(movies.id) AS compte')
            ->join('movies.realisateurs', 'directors')
            ->groupBy('directors.nom')
            ->addOrderBy('directors.nom')
                */
            /*->select('year(movies.dateSortie) AS sortie, COUNT(movies.id) AS compte')
            ->where('year(movies.dateSortie) = 1968 ')
            ->groupBy('sortie')
            */

            /*->select('movies.titre, MAX(year(movies.dateSortie)) AS sortie')
            ->groupBy('sortie')
            ->getQuery()
            ->getOneOrNullResult()*/
        ;

        return $movies;

    }





}
