<?php

namespace AppBundle\Repository;

/**
 * RealisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealisateurRepository extends \Doctrine\ORM\EntityRepository
{
    public function directorsQuery()
    {
        $directors = $this->createQueryBuilder('directors')
            ->select('directors.nom')
            ->getQuery()
            ->getResult()
        ;

        return $directors;

    }
}
